### ISSUE TITLE
Take one iteration at a time and/or fire callback at each iteration

### ISSUE THREAD

**Issue by alecjacobson** [sympiler/nasoq#5]
Is it possible to:

```
set up the NASOQ solver without taking iterations 
// do some of my code
take a single iteration of the NASOQ solver
// do some of my code
take a single iteration of the NASOQ solver
...
```
?

Alternatively, could I give a NASOQ a callback `mycode(x)` that will be called with the current solution/state of the NASOQ solver after each of its iteration?

**Comment by cheshmi** [comment]
It is not possible yet. Should be available hopefully soon.

**Comment by cheshmi** [comment]
@alecjacobson I put an example [here](https://github.com/sympiler/nasoq/blob/master/examples/nasoq_step_main.cpp). I hope it helps.
